name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
      name: Build
      runs-on: ubuntu-latest
  
      # list of steps to complete in the workflow, in order
      steps:
      # extend from these published, pre-configured actions
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            # the node version for the setup-node action
            node-version: 16.x
      # Install packages and run tests
      - run: npm ci
      - run: npm build
